# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{j_query_engine}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Matthias Folz}]
  s.date = %q{2011-08-11}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{folz@avarteq.de}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/helpers/j_query_builder.rb",
    "app/helpers/j_query_form.rb",
    "app/helpers/j_query_helper.rb",
    "app/helpers/scaffold_helper.rb",
    "app/views/layouts/_accord.html.erb",
    "app/views/layouts/_tab.html.erb",
    "app/views/layouts/accordion.html.erb",
    "app/views/layouts/dialog.html.erb",
    "app/views/layouts/entry.html.erb",
    "app/views/layouts/flash.html.erb",
    "app/views/layouts/flash/error.html.erb",
    "app/views/layouts/flash/notice.html.erb",
    "app/views/layouts/progressbar.html.erb",
    "app/views/layouts/tabs.html.erb",
    "init.rb",
    "j_query_engine.gemspec",
    "lib/extensions.rb",
    "lib/extensions/application_controller.rb",
    "lib/j_query_engine.rb",
    "lib/j_query_engine/engine.rb",
    "public/javascripts/jquery.js",
    "public/javascripts/jquery.min.js",
    "public/javascripts/jquery/jquery-1.6.1.js",
    "public/javascripts/jquery/jquery-ui-1.8.13.custom.min.js",
    "public/javascripts/jquery/jquery.mobile-1.0a4.1.js",
    "public/javascripts/jquery/jquery.ui.selectmenu.js",
    "public/javascripts/jquery_engine.js",
    "public/javascripts/jquery_engine_mobile.js",
    "public/javascripts/jquery_engine_ui.js",
    "spec/dummy/Rakefile",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/public/javascripts/application.js",
    "spec/dummy/public/javascripts/controls.js",
    "spec/dummy/public/javascripts/dragdrop.js",
    "spec/dummy/public/javascripts/effects.js",
    "spec/dummy/public/javascripts/prototype.js",
    "spec/dummy/public/javascripts/rails.js",
    "spec/dummy/public/stylesheets/.gitkeep",
    "spec/dummy/script/rails",
    "spec/integration/navigation_spec.rb",
    "spec/j_query_engine_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mafolz/j_query_engine}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

